version: '3'
services:
  natty_norvig1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: natty_norvig2
    command: python -u main.py
    image: bert_image
    ports:
      - "8080:80"
    links:
      - mongodb
  mongodb:
    image: mongo:4.2.11
    volumes:
      - mongodbdata:/data/db
    ports:
      - "27017:27017"


volumes:
  mongodbdata:
    driver: local
